language: python
python:
- 3.4

env:
  - QA
  - PROD
  
script: echo 5
script: echo 777

jobs:
  include:
  - stage: build
    if: branch = master
    script: echo 5
  - script: echo "test"
  - stage: deploy
    script: echo "deploy again"
    name "deploy2"
    
notifications:
  email:
    recipients: serg_m1@ukr.net
  
    on success: always
    on failure: always
  
  slack: 
    on success: change
    on failure: change
    
    rooms:
     - mikelearn:E868ULGEM1tpEtDJwl7ODigM#test2-travis_learning
#comments
