language: python
python:
- 3.4

#script
  #before script
  #script
script: 
  - mkdir ShortStory
  - touch KKK
  - echo 5
  
#after script
  #after success
  #after failure

#deploy
  #before deploy
  #deploy
  #after deploy
  
before_deploy: echo start

delpoy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
    
after_deploy: echo 50
